version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - fatcontext
    - forcetypeassert
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godoclint
    - gosec
    - mnd
    - musttag
    - nlreturn
    - noctx
    - noinlineerr
    - paralleltest
    - prealloc
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    errcheck:
      exclude-functions:
        - crypto/rand.Read
    funlen:
      statements: 60
      lines: 82
    gosmopolitan:
      allow-time-local: true
    ireturn:
      allow:
        - error
        - io.Reader
        - net/http.Handler
        - nkeys.KeyPair
    varnamelen:
      max-distance: 15
      ignore-names:
        - i
        - wg
      ignore-decls:
        - c *nftables.Conn
        - c nftables.Conn
        - ec *nats.Conn
        - f embed.FS
        - id string
        - ns *server.Server
        - r *http.Request
        - w http.ResponseWriter
  exclusions:
    warn-unused: true
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - gocognit
          - goconst
          - predeclared
          - revive
      - path: app/plexus-agent/cmd/*
        linters:
          - revive
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
